main: com.spherebattles.main.Main
version: 1.0
name: SphereBattles
api-version: 1.15

commands:
  Reset:
    description: test command
    aliases: []
  Rank:
    description: sets the player's rank
    aliases: []
  World:
    description: allows travel between worlds
    aliases: []
  Settag:
    description: sets a player's tag
    aliases: []
  List:
    description: nothing
    aliases: []